import { X, Printer, FileText, Loader2 } from 'lucide-react'
import { useState, useEffect } from 'react'

const TYPE_LABELS = {
  display: 'Display Theme',
  shelf_talker: 'Shelf Talker',
  escape_room: 'Escape Room',
  social_media: 'Social Media',
  signage: 'Signage / Flyer',
  program: 'Program Idea',
}

const TYPE_TINTS = {
  display: 'tint-indigo',
  shelf_talker: 'tint-emerald',
  escape_room: 'tint-rose',
  social_media: 'tint-violet',
  signage: 'tint-amber',
  program: 'tint-sky',
}

export default function CardModal({ card, onClose, onGenerateFullPlan }) {
  const [generating, setGenerating] = useState(false)
  const [fullPlan, setFullPlan] = useState(card.full_plan || null)
  const [genError, setGenError] = useState('')
  const content = card.content || {}

  useEffect(() => {
    const handleKeyDown = (e) => { if (e.key === 'Escape') onClose() }
    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [onClose])

  const isEscapeRoom = card.card_type === 'escape_room'
  const tintClass = TYPE_TINTS[card.card_type] || 'tint-indigo'

  const handleGenerateFullPlan = async () => {
    setGenerating(true)
    setGenError('')
    try {
      const plan = await onGenerateFullPlan(card)
      setFullPlan(plan)
    } catch (e) {
      console.error('Failed to generate full plan:', e)
      setGenError(e.message || 'Generation failed')
    } finally {
      setGenerating(false)
    }
  }

  // Escape HTML to prevent XSS when writing to print window
  const esc = (str) => {
    if (str == null) return ''
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;')
  }

  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    const html = fullPlan
      ? generateEscapeRoomHTML(card, fullPlan)
      : generateCardHTML(card)
    printWindow.document.write(html)
    printWindow.document.close()
    printWindow.print()
  }

  const generateCardHTML = (c) => {
    return `
<!DOCTYPE html>
<html>
<head>
  <title>${esc(TYPE_LABELS[c.card_type])} - Library Launchpad</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; line-height: 1.6; }
    h1 { color: #1d1d1f; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
    .type { display: inline-block; background: rgba(99,102,241,0.1); color: #6366f1; padding: 4px 12px; border-radius: 9999px; font-size: 14px; margin-bottom: 20px; }
    .content { background: #f5f5f7; padding: 20px; border-radius: 12px; }
    .field { margin-bottom: 16px; }
    .field label { font-weight: bold; display: block; color: #86868b; margin-bottom: 4px; }
    ul { margin: 8px 0; padding-left: 20px; }
    li { margin-bottom: 4px; }
  </style>
</head>
<body>
  <span class="type">${esc(TYPE_LABELS[c.card_type])}</span>
  <h1>${esc(content.headline || content.name || content.concept || TYPE_LABELS[c.card_type])}</h1>
  <div class="content">
    ${Object.entries(content).map(([key, val]) => {
      if (key === 'instagram' || key === 'facebook' || key === 'tiktok') return ''
      if (Array.isArray(val)) return `<div class="field"><label>${esc(key.replace(/_/g, ' '))}</label><ul>${val.map(v => `<li>${esc(v)}</li>`).join('')}</ul></div>`
      if (typeof val === 'object') return `<div class="field"><label>${esc(key.replace(/_/g, ' '))}</label>${esc(JSON.stringify(val))}</div>`
      return `<div class="field"><label>${esc(key.replace(/_/g, ' '))}</label><p>${esc(val)}</p></div>`
    }).join('')}
  </div>
  <p style="margin-top: 40px; color: #86868b; font-size: 12px;">Generated by Library Launchpad</p>
</body>
</html>`
  }

  const generateEscapeRoomHTML = (c, plan) => {
    const n = plan.narrative || {}
    const lf = plan.logicFlow || {}
    const rb = plan.roomBlueprint || {}
    const gm = plan.gameMasterCheatSheet || {}
    return `
<!DOCTYPE html>
<html>
<head>
  <title>${esc(n.mission || 'Escape Room')} - Library Launchpad</title>
  <style>
    @media print { .no-print { display: none; } }
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; line-height: 1.6; color: #1d1d1f; }
    h1 { color: #1d1d1f; border-bottom: 2px solid #f43f5e; padding-bottom: 10px; }
    h2 { color: #1d1d1f; margin-top: 24px; }
    h3 { color: #6366f1; }
    .meta { display: flex; gap: 20px; margin-bottom: 20px; color: #86868b; }
    .section { background: #f5f5f7; padding: 20px; border-radius: 12px; margin-bottom: 20px; }
    .puzzle { background: white; padding: 16px; border-left: 4px solid #6366f1; margin-bottom: 12px; border-radius: 0 8px 8px 0; }
    .aha { color: #f59e0b; font-style: italic; }
    .reward { color: #10b981; }
    .supplies { display: flex; flex-wrap: wrap; gap: 8px; }
    .supply { background: rgba(99,102,241,0.1); color: #6366f1; padding: 4px 12px; border-radius: 9999px; font-size: 14px; }
    .dep-step { margin-bottom: 8px; }
    .dep-step strong { color: #6366f1; }
    .hint-box { background: rgba(245,158,11,0.1); padding: 12px; border-radius: 8px; margin-bottom: 8px; }
    .hint-label { font-weight: bold; font-size: 13px; }
    .print-btn { position: fixed; top: 20px; right: 20px; background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white; border: none; padding: 12px 24px; border-radius: 12px; cursor: pointer; }
  </style>
</head>
<body>
  <button class="print-btn no-print" onclick="window.print()">🖨 Print</button>
  <h1>${esc(n.mission || 'Escape Room Design Document')}</h1>

  ${n.hook ? `<div class="section"><h2>📖 The Narrative</h2><p>${esc(n.hook)}</p>
    <p><strong>Mission:</strong> ${esc(n.mission || '')}</p>
    ${n.atmosphericCues ? `<p><em>Atmosphere: ${esc(n.atmosphericCues)}</em></p>` : ''}</div>` : ''}

  ${lf.structure ? `<div class="section"><h2>🔀 Puzzle Path (${esc(lf.structure)})</h2>
    ${lf.dependencyMap?.map(d => `<div class="dep-step"><strong>${esc(d.step)}.</strong> ${esc(d.puzzle)} → grants <em>${esc(d.grants)}</em> → unlocks ${esc(d.unlocks)}</div>`).join('') || ''}</div>` : ''}

  ${rb.layout ? `<div class="section"><h2>🗺️ Room Layout</h2><p>${esc(rb.layout)}</p>
    ${rb.stations?.map(s => `<h3>${esc(s.name)}</h3><p>${esc(s.description)}</p>
      ${s.interactableEnvironment?.length ? `<p><strong>Interactables:</strong> ${esc(s.interactableEnvironment.join(', '))}</p>` : ''}
      ${s.staticEnvironment?.length ? `<p><em>Atmosphere:</em> ${esc(s.staticEnvironment.join(', '))}</p>` : ''}`).join('') || ''}</div>` : ''}

  ${plan.puzzles?.length ? `<div class="section"><h2>🧩 Puzzles & Challenges</h2>
    ${plan.puzzles.map(p => `<div class="puzzle">
      <strong>Puzzle ${esc(p.number || '')}: ${esc(p.title)}</strong>
      <p><strong>Prompt:</strong> ${esc(p.prompt || '')}</p>
      <p><strong>Mechanic:</strong> ${esc(p.mechanic || '')}</p>
      <p><strong>Solution:</strong> ${esc(p.solutionLogic || '')}</p>
      ${p.ahaMoment ? `<p class="aha">💡 Aha! ${esc(p.ahaMoment)}</p>` : ''}
      ${p.reward ? `<p class="reward">🎁 Reward: ${esc(p.reward)}</p>` : ''}
      ${p.hints?.length ? `<p><em>Hints: ${esc(p.hints.join(' | '))}</em></p>` : ''}
    </div>`).join('')}</div>` : ''}

  ${plan.itemInventory?.length ? `<div class="section"><h2>📦 Prop Inventory</h2><div class="supplies">
    ${plan.itemInventory.map(i => `<span class="supply" title="${esc(i.specs || '')}">${esc(i.item)}${i.quantity > 1 ? ' ×' + esc(i.quantity) : ''}</span>`).join('')}</div></div>` : ''}

  ${gm.setupInstructions?.length ? `<div class="section"><h2>🔧 Setup Instructions</h2><ol>
    ${gm.setupInstructions.map(s => `<li>${esc(s)}</li>`).join('')}</ol></div>` : ''}

  ${gm.tieredHints?.length ? `<div class="section"><h2>💡 Tiered Hints</h2>
    ${gm.tieredHints.map(h => `<div class="hint-box"><p class="hint-label">${esc(h.puzzle)}</p>
      <p>1️⃣ Nudge: ${esc(h.hint1_nudge)}</p>
      <p>2️⃣ Insight: ${esc(h.hint2_insight)}</p>
      <p>3️⃣ Solution: ${esc(h.hint3_direct)}</p></div>`).join('')}</div>` : ''}

  ${gm.resetChecklist?.length ? `<div class="section"><h2>🔄 Reset Checklist</h2><ol>
    ${gm.resetChecklist.map(s => `<li>${esc(s)}</li>`).join('')}</ol></div>` : ''}

  <p style="margin-top: 40px; color: #86868b; font-size: 12px;">Generated by Library Launchpad</p>
</body>
</html>`
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{background: 'rgba(0,0,0,0.4)', backdropFilter: 'blur(4px)'}} onClick={onClose}>
      <div
        role="dialog"
        aria-modal="true"
        aria-label={content.headline || content.name || content.concept || TYPE_LABELS[card.card_type]}
        className="bg-card rounded-xl border border-default max-w-2xl w-full max-h-[90vh] overflow-y-auto overscroll-contain"
        style={{boxShadow: 'var(--shadow-modal)'}}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-subtle">
          <span className={`text-[0.6875rem] font-semibold px-2.5 py-1 rounded-full ${tintClass}`}>
            {TYPE_LABELS[card.card_type]}
          </span>
          <button onClick={onClose} aria-label="Close modal" className="p-2 hover:bg-hover rounded-lg transition-all duration-250 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-solid)]">
            <X className="w-5 h-5 text-tertiary" />
          </button>
        </div>

        {/* Content */}
        <div className="px-6 py-6 space-y-5">
          <h2 className="text-xl font-bold text-primary">
            {content.headline || content.name || content.concept || TYPE_LABELS[card.card_type]}
          </h2>

          {/* Show full content fields */}
          {Object.entries(content).map(([key, val]) => {
            if (key === 'instagram' || key === 'facebook' || key === 'tiktok') return null
            if (typeof val === 'object' && val !== null && !Array.isArray(val)) return null

            return (
              <div key={key}>
                <label className="section-label">
                  {key.replace(/_/g, ' ')}
                </label>
                {Array.isArray(val) ? (
                  <ul className="mt-1.5 space-y-1">
                    {val.map((v, i) => (
                      <li key={i} className="text-secondary text-sm leading-relaxed">• {typeof v === 'string' ? v : JSON.stringify(v)}</li>
                    ))}
                  </ul>
                ) : (
                  <p className="text-secondary text-sm mt-1 leading-relaxed">{val}</p>
                )}
              </div>
            )
          })}

          {/* Full escape room plan */}
          {fullPlan && (
            <div className="mt-6 p-5 bg-page rounded-xl border border-default space-y-6">
              <h3 className="font-semibold text-primary">Full Escape Room Design Document</h3>

              {fullPlan.narrative && (
                <div>
                  <h4 className="accent-solid font-medium mb-2">📖 The Narrative</h4>
                  <p className="text-secondary text-sm whitespace-pre-line leading-relaxed">{fullPlan.narrative.hook}</p>
                  <p className="text-rose-500 text-sm mt-2 font-medium">🎯 Mission: {fullPlan.narrative.mission}</p>
                  {fullPlan.narrative.atmosphericCues && (
                    <p className="text-tertiary text-xs mt-1 italic">🎵 {fullPlan.narrative.atmosphericCues}</p>
                  )}
                </div>
              )}

              {fullPlan.logicFlow && (
                <div>
                  <h4 className="accent-solid font-medium mb-2">🔀 Puzzle Path: {fullPlan.logicFlow.structure}</h4>
                  {fullPlan.logicFlow.dependencyMap?.map((d, i) => (
                    <div key={i} className="text-sm text-secondary flex gap-2 items-start leading-relaxed">
                      <span className="accent-solid font-mono font-semibold">{d.step}.</span>
                      <span><strong className="text-primary">{d.puzzle}</strong> → grants <em className="text-amber-500">{d.grants}</em> → unlocks {d.unlocks}</span>
                    </div>
                  ))}
                </div>
              )}

              {fullPlan.roomBlueprint && (
                <div>
                  <h4 className="accent-solid font-medium mb-2">🗺️ Room Layout</h4>
                  <p className="text-secondary text-sm mb-3 leading-relaxed">{fullPlan.roomBlueprint.layout}</p>
                  {fullPlan.roomBlueprint.stations?.map((s, i) => (
                    <div key={i} className="bg-card rounded-lg p-3.5 mb-2 border border-subtle">
                      <p className="text-sm font-medium text-primary">{s.name}</p>
                      <p className="text-xs text-tertiary mt-0.5">{s.description}</p>
                      {s.interactableEnvironment?.length > 0 && (
                        <p className="text-xs text-emerald-500 mt-1">🔧 {s.interactableEnvironment.join(', ')}</p>
                      )}
                    </div>
                  ))}
                </div>
              )}

              {fullPlan.puzzles?.map((p, i) => (
                <div key={i} className="bg-card rounded-lg p-4 border-l-4 border-[var(--accent-solid)]">
                  <h4 className="accent-solid font-medium">Puzzle {p.number || i + 1}: {p.title}</h4>
                  <p className="text-secondary text-sm mt-1"><strong className="text-primary">What you see:</strong> {p.prompt || p.description}</p>
                  <p className="text-tertiary text-xs mt-1">⚙️ Mechanic: {p.mechanic}</p>
                  <p className="text-secondary text-sm mt-1"><strong className="text-primary">Solution:</strong> {p.solutionLogic || p.solution}</p>
                  {p.ahaMoment && <p className="text-amber-500 text-xs mt-1">💡 Aha! {p.ahaMoment}</p>}
                  {p.reward && <p className="text-emerald-500 text-xs mt-1">🎁 Reward: {p.reward}</p>}
                  {p.hints?.length > 0 && (
                    <p className="text-tertiary text-xs mt-1">💡 Hints: {p.hints.join(', ')}</p>
                  )}
                </div>
              ))}

              {fullPlan.itemInventory?.length > 0 && (
                <div>
                  <h4 className="accent-solid font-medium mb-2">📦 Prop Inventory</h4>
                  <div className="flex flex-wrap gap-2">
                    {fullPlan.itemInventory.map((item, i) => (
                      <span key={i} className="text-xs text-secondary bg-hover px-2.5 py-1 rounded-full border border-subtle" title={item.specs}>
                        {item.item}{item.quantity > 1 ? ` ×${item.quantity}` : ''}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {fullPlan.gameMasterCheatSheet && (
                <div>
                  <h4 className="accent-solid font-medium mb-2">📋 Game Master's Cheat Sheet</h4>
                  {fullPlan.gameMasterCheatSheet.setupInstructions?.length > 0 && (
                    <div className="mb-3">
                      <p className="section-label mb-1">Setup</p>
                      <ul className="text-sm text-secondary list-disc list-inside space-y-0.5">
                        {fullPlan.gameMasterCheatSheet.setupInstructions.map((s, i) => <li key={i}>{s}</li>)}
                      </ul>
                    </div>
                  )}
                  {fullPlan.gameMasterCheatSheet.tieredHints?.map((h, i) => (
                    <div key={i} className="mb-2 bg-card rounded-lg p-3 border border-subtle">
                      <p className="text-xs font-semibold text-amber-500">Hints for: {h.puzzle}</p>
                      <p className="text-xs text-tertiary mt-0.5">1️⃣ {h.hint1_nudge}</p>
                      <p className="text-xs text-tertiary">2️⃣ {h.hint2_insight}</p>
                      <p className="text-xs text-rose-400">3️⃣ {h.hint3_direct}</p>
                    </div>
                  ))}
                  {fullPlan.gameMasterCheatSheet.resetChecklist?.length > 0 && (
                    <div>
                      <p className="section-label mb-1">Reset Checklist</p>
                      <ol className="text-sm text-secondary list-decimal list-inside space-y-0.5">
                        {fullPlan.gameMasterCheatSheet.resetChecklist.map((s, i) => <li key={i}>{s}</li>)}
                      </ol>
                    </div>
                  )}
                </div>
              )}

              {fullPlan.steps?.length > 0 && (
                <div>
                  <h4 className="accent-solid font-medium">Setup Steps</h4>
                  <ol className="text-secondary text-sm space-y-1 mt-1">
                    {fullPlan.steps.map((s, i) => <li key={i}>{i + 1}. {s}</li>)}
                  </ol>
                </div>
              )}
              {fullPlan.materials?.length > 0 && (
                <div className="mt-4">
                  <h4 className="accent-solid font-medium">Additional Materials</h4>
                  <div className="flex flex-wrap gap-2 mt-2">
                    {fullPlan.materials.map((m, i) => (
                      <span key={i} className="text-xs text-secondary bg-hover px-2.5 py-1 rounded-full border border-subtle">{m}</span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="flex gap-3 px-6 py-4 border-t border-subtle">
          {isEscapeRoom && !fullPlan && (
            <>
              {genError && (
                <p className="text-red-500 text-sm mb-2">{genError}</p>
              )}
              <button
                onClick={handleGenerateFullPlan}
                disabled={generating}
                className="btn-gradient flex-1 py-2.5 px-4 rounded-lg font-medium flex items-center justify-center gap-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-solid)]"
              >
                {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
                {generating ? 'Generating…' : 'Generate Full Escape Room Plan (10 credits)'}
              </button>
            </>
          )}
          <button
            onClick={handlePrint}
            className="py-2.5 px-4 bg-hover text-secondary hover:text-primary border border-default rounded-lg font-medium transition-all duration-250 flex items-center justify-center gap-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-solid)]"
          >
            <Printer className="w-4 h-4" />
            Print / PDF
          </button>
        </div>
      </div>
    </div>
  )
}
