import { useEffect } from 'react'
import { X, ArrowRight } from 'lucide-react'

export default function WelcomeModal({ campaigns, onSelect, onClose, onSignUp }) {
  useEffect(() => {
    const handleKeyDown = (e) => { if (e.key === 'Escape') onClose() }
    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [onClose])

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{background: 'rgba(0,0,0,0.4)', backdropFilter: 'blur(4px)'}}>
      <div role="dialog" aria-modal="true" aria-label="Pick an example campaign" className="bg-card rounded-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto overscroll-contain border border-default" style={{boxShadow: 'var(--shadow-modal)'}}>
        <div className="px-6 py-5 border-b border-subtle flex items-start justify-between">
          <div>
            <p className="text-sm accent-solid font-medium mb-1">Browsing as guest</p>
            <h2 className="text-xl font-bold text-primary">See what Launchpad can do</h2>
            <p className="text-secondary text-sm mt-1">
              Pick a campaign below to explore. Each one was generated by the same AI that powers your real campaigns — display themes, escape rooms, social posts, programs, and more.
            </p>
          </div>
          <button onClick={onClose} aria-label="Close" className="p-2 hover:bg-hover rounded-lg transition-all duration-250 flex-shrink-0 mt-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-solid)]">
            <X className="w-5 h-5 text-tertiary" />
          </button>
        </div>

        <div className="px-6 py-5 space-y-3">
          {campaigns.map((c, i) => (
            <button
              key={i}
              onClick={() => onSelect(c)}
              className="w-full text-left p-4 rounded-xl border border-default hover:border-strong bg-page hover:bg-hover transition-all duration-250 group focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-solid)]"
            >
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-semibold text-primary">{c.topic}</p>
                  <p className="text-xs text-tertiary mt-0.5">
                    {c.cards.length} cards · {c.cards.map(card => {
                      const labels = { display: 'Display', shelf_talker: 'Shelf Talker', escape_room: 'Escape Room', social_media: 'Social', signage: 'Signage', program: 'Program' }
                      return labels[card.card_type] || card.card_type
                    }).filter((v, i, a) => a.indexOf(v) === i).join(' · ')}
                  </p>
                  <p className="text-xs text-secondary mt-1 line-clamp-1">
                    {c.media.map(m => m.title).join(', ')}
                  </p>
                </div>
                <ArrowRight className="w-4 h-4 text-tertiary group-hover:text-primary transition-colors flex-shrink-0" />
              </div>
            </button>
          ))}
        </div>

        <div className="px-6 py-4 border-t border-subtle flex items-center justify-between">
          <p className="text-xs text-tertiary">Sign up to generate custom campaigns for any topic.</p>
          <button
            onClick={onSignUp}
            className="btn-gradient px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-solid)]"
          >
            Sign Up Free
          </button>
        </div>
      </div>
    </div>
  )
}
